In [44]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores : ndarray | None = None
#scores_df : DataFrame | None = None

scores:ndarray = np.random.randint(50, 101, size=(100, 5))
scores_df:DataFrame = pd.DataFrame(scores, 
                        columns = ['國文', '英文', '數學', '地理', '歷史'], 
                        index = range(1, 101) )
names_df : DataFrame = pd.read_csv('student_data.csv')
scores_df[['姓名','年齡']] = names_df[['姓名','年齡']].head(n=100).values
scores_df = scores_df[['姓名', '年齡','國文', '英文', '數學', '地理', '歷史']]
#print(type(scores))
#print(scores.shape)
#選取欄
scores_df[['姓名', '年齡']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名  年齡  國文  英文  數學  地理  歷史
6   黃美玲  25  87  91  83  66  72
7   趙國強  50  65  77  99  94  97
8   孫雅婷  29  93  50  79  86  64
9   周正雄  38  63  71  66  72  75
10  吳淑芬  45  65  57  64  86  98

In [40]:
scores_df[scores_df['姓名'] == '黃美玲']
#scores_df[scores_df['國文'] < 60]
scores_df.query("年齡 > 30 and 國文 < 60")

     姓名  年齡  國文  英文  數學  地理  歷史   總分
10  吳淑芬  45  56  93  90  66  93  398
19  林俊傑  34  57  85  57  79  93  371
44  邱淑芬  42  51  88  74  84  99  396
53  章大慶  45  51  80  65  78  51  325
61  連志遠  44  56  79  74  89  66  364
66  龔淑芬  46  55  98  57  75  62  347
67  程大維  32  52  53  50  88  96  339
81  伍美玲  31  59  84  91  98  71  403
91  蘇大維  32  58  93  96  74  58  379
99  溫惠君  33  52  60  51  53  57  273

In [48]:
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False, method='min')
scores_df.sort_values(by = '排名')

     姓名  年齡  國文  英文  數學   地理   歷史   總分    平均     排名
98  黃建興  34  95  97  99   85   93  469  93.8    1.0
81  伍美玲  31  85  94  90   95   90  454  90.8    2.0
74  雷國強  49  89  96  99   64  100  448  89.6    3.0
4   李靜宜  22  94  75  89  100   87  445  89.0    4.0
5   王志豪  30  97  87  98   93   70  445  89.0    4.0
..  ...  ..  ..  ..  ..  ...  ...  ...   ...    ...
33  詹家銘  38  70  71  75   52   53  321  64.2   96.0
99  溫惠君  33  53  83  54   75   55  320  64.0   97.0
75  錢淑芬  37  59  63  77   61   59  319  63.8   98.0
40  白美玲  31  50  79  66   64   50  309  61.8   99.0
68  薛惠敏  31  55  59  60   63   60  297  59.4  100.0

[100 rows x 10 columns]