In [54]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores : ndarray | None = None
#scores_df : DataFrame | None = None

scores:ndarray = np.random.randint(50, 101, size=(100, 5))
scores_df:DataFrame = pd.DataFrame(scores, 
                        columns = ['國文', '英文', '數學', '地理', '歷史'], 
                        index = range(1, 101) )
names_df : DataFrame = pd.read_csv('student_data.csv')
scores_df[['姓名','年齡', '性別']] = names_df[['姓名','年齡', '性別']].head(n=100).values
scores_df = scores_df[['姓名','性別', '年齡','國文', '英文', '數學', '地理', '歷史']]
#print(type(scores))
#print(scores.shape)
#選取欄
scores_df[['姓名', '年齡']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  年齡  國文  英文  數學  地理  歷史
6   黃美玲  女  25  99  77  84  61  67
7   趙國強  男  50  52  53  88  52  52
8   孫雅婷  女  29  59  85  72  56  61
9   周正雄  男  38  68  73  54  86  90
10  吳淑芬  女  45  93  94  74  58  55

In [55]:
scores_df[scores_df['姓名'] == '黃美玲']
#scores_df[scores_df['國文'] < 60]
scores_df.query("年齡 > 30 and 國文 < 60")

     姓名 性別  年齡  國文  英文   數學  地理  歷史
7   趙國強  男  50  52  53   88  52  52
11  鄭志強  男  33  50  72   72  79  51
21  葉宏達  男  48  59  83   67  88  72
25  梁家豪  男  43  52  55   78  71  76
30  蔡淑惠  女  40  57  90   57  62  53
44  邱淑芬  女  42  55  71   63  60  82
58  紀惠君  女  33  50  71  100  63  84
79  曾惠君  女  36  58  96   82  85  95
81  伍美玲  女  31  56  62   88  66  70
88  蔡國強  男  47  51  98   53  87  75

In [56]:
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False, method='min')
scores_df.sort_values(by = '排名')

     姓名 性別  年齡  國文  英文  數學  地理  歷史   總分    平均     排名
54  曹雅惠  女  25  96  96  81  95  83  451  90.2    1.0
69  侯志剛  男  40  93  98  97  81  68  437  87.4    2.0
14  陳建豪  男  24  90  91  91  75  82  429  85.8    3.0
15  楊玉珍  女  36  78  84  90  89  84  425  85.0    4.0
60  黃雅婷  女  27  67  87  98  97  74  423  84.6    5.0
..  ... ..  ..  ..  ..  ..  ..  ..  ...   ...    ...
78  閻志成  男  42  60  64  67  83  53  327  65.4   96.0
36  方雅婷  女  29  71  50  55  80  69  325  65.0   97.0
11  鄭志強  男  33  50  72  72  79  51  324  64.8   98.0
30  蔡淑惠  女  40  57  90  57  62  53  319  63.8   99.0
7   趙國強  男  50  52  53  88  52  52  297  59.4  100.0

[100 rows x 11 columns]

In [57]:
from pandas import Series
def calulate(s:Series)-> int:
    n = (s < 60).sum()
    return n
    
scores_df['及格的科目數'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(calulate,axis=1)
scores_df

      姓名 性別  年齡  國文  英文   數學  地理  歷史   總分    平均    排名  及格的科目數
1    林小明  男  28  86  88   65  80  76  395  79.0  26.0       0
2    陳曉華  女  35  66  66   78  87  77  374  74.8  49.0       0
3    張大偉  男  42  79  72   70  87  93  401  80.2  19.0       0
4    李靜宜  女  22  51  87   83  96  82  399  79.8  20.0       1
5    王志豪  男  30  78  60   61  90  57  346  69.2  78.0       1
..   ... ..  ..  ..  ..  ...  ..  ..  ...   ...   ...     ...
96   胡曉潔  女  30  91  95   70  55  75  386  77.2  39.0       1
97   梁美玲  女  37  89  61   63  53  75  341  68.2  81.0       1
98   黃建興  男  34  73  94  100  82  71  420  84.0  11.0       0
99   溫惠君  女  33  79  81   55  77  51  343  68.6  79.0       2
100  賴志成  男  43  94  87   76  78  74  409  81.8  15.0       0

[100 rows x 12 columns]

In [ ]:
def get_failing_subjects(row):
    subjects = ['國文', '英文', '數學', '地理', '歷史']
    failing = [subj for subj in subjects if row[subj] < 60]    
    return ','.join(failing) if failing else "無"
    
scores_df["不及格的科目名稱"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(get_failing_subjects,axis=1)
scores_df

      姓名 性別  年齡  國文  英文   數學  地理  歷史   總分    平均    排名  及格的科目數 不及格的科目名稱
1    林小明  男  28  86  88   65  80  76  395  79.0  26.0       0        無
2    陳曉華  女  35  66  66   78  87  77  374  74.8  49.0       0        無
3    張大偉  男  42  79  72   70  87  93  401  80.2  19.0       0        無
4    李靜宜  女  22  51  87   83  96  82  399  79.8  20.0       1       國文
5    王志豪  男  30  78  60   61  90  57  346  69.2  78.0       1       歷史
..   ... ..  ..  ..  ..  ...  ..  ..  ...   ...   ...     ...      ...
96   胡曉潔  女  30  91  95   70  55  75  386  77.2  39.0       1       地理
97   梁美玲  女  37  89  61   63  53  75  341  68.2  81.0       1       地理
98   黃建興  男  34  73  94  100  82  71  420  84.0  11.0       0        無
99   溫惠君  女  33  79  81   55  77  51  343  68.6  79.0       2    數學,歷史
100  賴志成  男  43  94  87   76  78  74  409  81.8  15.0       0        無

[100 rows x 13 columns]