In [13]:
import numpy as np
import pandas as pd

data = pd.Series(np.random.randn(9),
                index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                       [1, 2, 3, 1, 2, 3, 1, 2, 3]])
data

a  1   -1.315230
   2    0.159942
   3   -0.842330
b  1    0.404222
   2    0.062376
c  3    0.748199
   1    0.147240
d  2    1.998994
   3    1.552355
dtype: float64

In [14]:
data1 = data.unstack()
data1

          1         2         3
a -1.315230  0.159942 -0.842330
b  0.404222  0.062376       NaN
c  0.147240       NaN  0.748199
d       NaN  1.998994  1.552355

In [15]:
data1.stack()

a  1   -1.315230
   2    0.159942
   3   -0.842330
b  1    0.404222
   2    0.062376
c  1    0.147240
   3    0.748199
d  2    1.998994
   3    1.552355
dtype: float64

In [16]:
import numpy as np
import pandas as pd

frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                    index=[['a','a','b','b'],[1, 2, 1, 2]],
                    columns=[['台北','台北','台中'],['Green','Red','Green']])
frame.index.names = ['key1', 'key2']
frame.columns.names = ['縣市','顏色']
frame

縣市           台北        台中
顏色        Green Red Green
key1 key2
a    1        0   1     2
     2        3   4     5
b    1        6   7     8
     2        9  10    11

In [17]:
frame1 = frame.stack(['顏色','縣市'])
frame1

C:\Users\user\AppData\Local\Temp\ipykernel_18744\3801192309.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  frame1 = frame.stack(['顏色','縣市'])

key1  key2  顏色     縣市
a     1     Green  台北     0.0
                   台中     2.0
            Red    台北     1.0
      2     Green  台北     3.0
                   台中     5.0
            Red    台北     4.0
b     1     Green  台北     6.0
                   台中     8.0
            Red    台北     7.0
      2     Green  台北     9.0
                   台中    11.0
            Red    台北    10.0
dtype: float64

In [18]:
frame1.unstack('key1')

key1             a     b
key2 顏色    縣市
1    Green 台北  0.0   6.0
           台中  2.0   8.0
     Red   台北  1.0   7.0
2    Green 台北  3.0   9.0
           台中  5.0  11.0
     Red   台北  4.0  10.0

In [20]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'key1':['a', 'a', 'b', 'b', 'a'],
                  'key2':['one', 'two', 'one', 'two', 'one'],
                  'data1': np.random.randn(5),
                  'data2':np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one  0.055252 -0.547219
1    a  two -0.706683  0.936414
2    b  one -1.000554 -1.563309
3    b  two -1.093363 -0.502060
4    a  one  1.075945 -0.563282

In [21]:
df.groupby('key1').sum()

           key2     data1     data2
key1
a     onetwoone  0.424514 -0.174088
b        onetwo -2.093917 -2.065368

In [22]:
df1 = df.groupby(['key1','key2']).sum()
df1.columns.name = "data"
df1

data          data1     data2
key1 key2
a    one   1.131197 -1.110502
     two  -0.706683  0.936414
b    one  -1.000554 -1.563309
     two  -1.093363 -0.502060

In [23]:
df1.stack().unstack(['key1','data'])

key1         a                   b
data     data1     data2     data1     data2
key2
one   1.131197 -1.110502 -1.000554 -1.563309
two  -0.706683  0.936414 -1.093363 -0.502060